// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6TO-n6IYhKWhd1o6CHQttUhDfsLdttOA',
    appId: '1:225632634486:web:e21e5440577c7eee574157',
    messagingSenderId: '225632634486',
    projectId: 'my-money-mentor-1a14f',
    authDomain: 'my-money-mentor-1a14f.firebaseapp.com',
    storageBucket: 'my-money-mentor-1a14f.firebasestorage.app',
    measurementId: 'G-JXRRZE5SSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-32QE-K_5V7RYaSpiYmzjf2ktYUNJdRE',
    appId: '1:225632634486:android:ca5ae00d8292f7d2574157',
    messagingSenderId: '225632634486',
    projectId: 'my-money-mentor-1a14f',
    storageBucket: 'my-money-mentor-1a14f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0NBwd-39jp3j3BSdQc4wBd4Jd5ldHqM',
    appId: '1:225632634486:ios:f1e07ec2f3240672574157',
    messagingSenderId: '225632634486',
    projectId: 'my-money-mentor-1a14f',
    storageBucket: 'my-money-mentor-1a14f.firebasestorage.app',
    iosBundleId: 'com.example.mymoneymentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0NBwd-39jp3j3BSdQc4wBd4Jd5ldHqM',
    appId: '1:225632634486:ios:f1e07ec2f3240672574157',
    messagingSenderId: '225632634486',
    projectId: 'my-money-mentor-1a14f',
    storageBucket: 'my-money-mentor-1a14f.firebasestorage.app',
    iosBundleId: 'com.example.mymoneymentor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6TO-n6IYhKWhd1o6CHQttUhDfsLdttOA',
    appId: '1:225632634486:web:d4092f54bb769e63574157',
    messagingSenderId: '225632634486',
    projectId: 'my-money-mentor-1a14f',
    authDomain: 'my-money-mentor-1a14f.firebaseapp.com',
    storageBucket: 'my-money-mentor-1a14f.firebasestorage.app',
    measurementId: 'G-8SJ3X6D0L2',
  );
}
